// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ersrbvsildiudrojsebk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyc3JidnNpbGRpdWRyb2pzZWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDI5MDksImV4cCI6MjA2MjY3ODkwOX0.C-lItE02rQkSXJX6tjt8IuxGUTcLfQ76XCXU9ZNPtKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);